Новые антагонисты и возможность таскать вещи безруким
13lackHawk/space-station-14 pull request #91
Opened 2024-03-08 13:55 UTC by NIKforest

Добавление новый антагонистов, которые будут спавниться админами во время игры. Уже добавлены в википедию.
Некоторые мобы могут таскать не прикрученные вещи или других существ. Это улучшит взаимодействие с игроками. Также тарантулы теперь смогут складывать тела добыч в одну кучу по их желанию. Карпы дракона смогут таскать жертв к дракону.
Описание всех добавленных антагонистов:
Интекорри - монстр технических помещений. Он может появиться в начале смены. Снимает вещи с игроков если те стоят у него, если игроки сопротивляются, может забрать их вещи силой, либо пойти по своим делам. Имеет мощные и сильные руки, которые могут без проблем ломать стены и кромсать людей. Мелкий антагонист.

Ликвид - живая газировка. Он любит газировку. Он любит пожирать грубых людей. Появляется на станции в помощью разлитой газировка облучённой радиации и космической магии. Безобиден если не злить его. Если ликвид сожрал человека, это отличный повод расстрелять его. Мелкий антагонист.

Космические черти - новая разработка cubersun для помехи работы конкурентов. Это существа, созданные компанией cybersun, для помехи работы станции. Они находят станцию когда смена на ней длиться в среднем полтора часа и начинают мешать ей. С Агентами синдиката они не сотрудничают, их обучили только воровству всего что есть на станции. У обоих чертей есть особый имплант сканер массы, с помощью него они находят станции НТ. То-есть они просто летают по космосу в надежде найти станцию. У большого черта есть особый редспейс рюкзак, туда он помещает украденное. Задача чертёнка это прикрытие и помощь в воровстве. В отличии от чёрта, они могут брать сразу 2 предмета. Когда они что-либо взяли, они относят это черту на хранение. Если станция долго не может избавиться от чертей, то они могут поселиться на ближайшем обломке, храня там свои вещи. Если черта убивают, чертята улетают в космос, а если они поселились на обломке, то тогда они будут охранять все украденные вещи. После того как экипаж станции покидает станцию, чертята сообщает cybersun о этих вещах. Один из чертей просто возвращается на место станции cybersun и сообщает координаты, после чего все вещи забирают. Они не имеют летальной силы, так как настроенный на отвлечение станции, что бы СБ бросили силы на уничтожение чертей, а агенты синдиката смогут с большим шансом выполнить свои цели. При убийстве космического черта, с него выпадет особый рюкзак, который вмещает в себя много вещей. Вещи они берут своими жгутиками. Стреляют энергией из глаза. Крупный антагонист.

Призрачные роли:
Маленький паучок - крупное насекомое, цель которого заключается в охоте на маленьких животных. Не несёт угрозы экипажу станции, если его не трогать. Можно подкормить кинув ему живую мышь, после чего получите его одобрение и дружелюбное отношение к вам. Можно взять на ручки. Нейтральное насекомое, которые не должно просто так нападать на экипаж, не антагонист.

Игрушки админов:
Эти роли могут спавнить исключительно админы для своих целей. У них нету лора или причин появления. Админ сам решит когда их заспавнить. Админы сами решают как отыгрывать.

Батя Хонк - накаченный клоун. Имеет 300 здоровья, падает в крит при 200. Урон 20 blunt.
Тень - жуткая фигура с белыми глазами. Здоровье 5, урон 5 blunt.
Мобы которые были изменены
-->

:cl:
- add: новый мелкий антагонист: Интекорри
- add: новый мелкий антагонист: Ликвид
- add: новый крупный антагонисты: космические черти
- add: возможность таскать вещи некоторым мобам без рук.
- remove: убрана возможность таскать вещи маленьким мобам, на пример: мыши, курицы, утки, тараканы, бабочки, пчёлы.

Тесты новых мобов проводила Лемирда, также эти существа были добавлены в игру прототипами и ошибок не было.

2024-03-08 14:20 UTC, Lemirda commented
```yaml
- type: speechSounds
  id: LiquidSpeech
  saySound:
    path: /Uploaded/Audio/Andromeda/LiquidSpeech/say.ogg
  askSound:
    path: /Uploaded/Audio/Andromeda/LiquidSpeech/ask.ogg
  exclaimSound:
    path: /Uploaded/Audio/Andromeda/LiquidSpeech/exclaim.ogg
```

2024-03-08 14:21 UTC, Lemirda commented
Запрашиваю изменения

2024-03-08 14:23 UTC, Lemirda commented
```yaml
sprite:/Andromeda/......
```

2024-03-08 14:23 UTC, Lemirda commented
Запришваю изменения

2024-03-08 14:43 UTC, Lemirda requested changes
Убрать безобразие с `/Uploaded/`, изменить на нормальный путь `/Audio/`.
Исправить `sprite: /Andromeda/...` на, `sprite: Andromeda/...`.

2024-03-08 14:46 UTC, Lemirda commented on Resources/Prototypes/Andromeda/NIKforest's Prototypes/MrProperMobs.yml
> +
Убрать лишние отступы

2024-03-08 14:47 UTC, Lemirda requested changes
[Отступы](https://github.com/13lackHawk/space-station-14/pull/91#discussion_r1517811717)

2024-03-08 14:54 UTC, Lemirda reviewed
Uploaded + Отступы

2024-03-08 14:54 UTC, Lemirda commented on Resources/Prototypes/Andromeda/NIKforest's Prototypes/MrProperMobs.yml
> +
Лишний отступ

2024-03-08 14:54 UTC, Lemirda commented on Resources/Prototypes/Andromeda/NIKforest's Prototypes/MrProperMobs.yml
> +    path: /Uploaded/Audio/Andromeda/LiquidSpeech/say.ogg
```suggestion
    path: /Audio/Andromeda/LiquidSpeech/say.ogg
```

2024-03-08 14:54 UTC, Lemirda commented on Resources/Prototypes/Andromeda/NIKforest's Prototypes/MrProperMobs.yml
> +    path: /Uploaded/Audio/Andromeda/LiquidSpeech/ask.ogg
```suggestion
    path: /Audio/Andromeda/LiquidSpeech/ask.ogg
```

2024-03-08 14:54 UTC, Lemirda commented on Resources/Prototypes/Andromeda/NIKforest's Prototypes/MrProperMobs.yml
> +    path: /Uploaded/Audio/Andromeda/LiquidSpeech/exclaim.ogg
```suggestion
    path: /Audio/Andromeda/LiquidSpeech/exclaim.ogg
```

2024-03-08 14:54 UTC, Lemirda commented on Resources/Prototypes/Andromeda/NIKforest's Prototypes/MrProperMobs.yml
> +       path: /Uploaded/Audio/Andromeda/Liquid/scream.ogg
```suggestion
       path: /Audio/Andromeda/Liquid/scream.ogg
```

2024-03-08 15:00 UTC, Lemirda commented
Уберите отступы, например как на 899 строчке.

2024-03-08 15:03 UTC, Lemirda approved these changes
Сойдёт

2024-03-08 17:40 UTC, Lemirda commented
Укажите :cl:

2024-03-09 11:43 UTC, NIKforest commented
Как?

2024-03-09 11:49 UTC, Lemirda commented
```
🆑 <ИМЯ>

add: новый мелкий антагонист: Интекорри
add: новый мелкий антагонист: Ликвид
add: новый крупный антагонисты: космические черти
add: возможность таскать вещи некоторым мобам без рук.
remove: убрана возможность таскать вещи маленьким мобам, на пример: мыши, курицы, утки, тараканы, бабочки, пчёлы.
```

2024-03-10 17:18 UTC, AwareFoxy commented
ну ты хотя бы геймрул добавил который бы спавнил этих самых антагов в раунде

2024-03-11 14:28 UTC, Lemirda commented
@AwareFoxy 
Я думаю пойзже я займусь этим

2024-03-23 17:09 UTC, merged